version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      npm install
  build:
    commands:
      npm run build
      npm run test -- --watchAll=false

reports:
  jest_reports:
    files:
      - report.xml
    base-directory: build
    file-format: JunitXml

artifacts:
  files:
    - '**/*'
  base-directory: build
