site_name: Retro Carnage
site_url: http://www.retro-carnage.net/
nav:
  - Home: index.md
  - Development:
    - Overview: development/index.md
  - Download: downloads/index.md
  - License: license.md
theme:
  name: material
  highlightjs: true
  prev_next_buttons_location: none