site_name: Retro Carnage
site_url: http://www.retro-carnage.net/
nav:
  - Home: index.md
  - Download: downloads/index.md
  - Screenshots: screenshots.md
  - Development:
    - Overview: development/index.md
    - Game:
      - Build and run: development/game/build-and-run.md
    - Editor:
      - Build and run: development/editor/build-and-run.md
  - License: license.md
theme:
  name: material
  highlightjs: true
  prev_next_buttons_location: none