site_name: Retro Carnage
nav:
  - Home: index.md
  - Frontend: frontend.md
  - Backend: backend.md
  - About: about.md
  - License: license.md
theme:
  name: readthedocs
  highlightjs: true
  prev_next_buttons_location: none