site_name: Retro Carnage
site_url: http://docs.retro-carnage.net/
nav:
  - Home: index.md
  - Development:
    - development/index.md
  - Download:
    - downloads/index.md     
  - License: license.md
theme:
  name: readthedocs
  highlightjs: true
  prev_next_buttons_location: none