site_name: Retro Carnage
site_url: http://www.retro-carnage.net/
site_dir: '../../generated/en'
docs_dir: '../../docs/en'

repo_url: https://github.com/Retro-Carnage-Team/retro-carnage-website
edit_uri: edit/master/docs/en/

theme:
  custom_dir: '../../overrides/'
  favicon: assets/images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
  highlightjs: true
  language: en  
  name: material  
  prev_next_buttons_location: none

extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:                                         
      lang: en

nav:
  - Home: index.md
  - Blog (🇩🇪): /de/blog/index.html
  - Download: download.md
  - Screenshots: screenshots.md
  - Development:
    - Overview: development/index.md
    - Game:
      - Build and run: development/game/build-and-run.md
      - Assets:
        - Weapon configurations: development/game/assets/weapons-configurations.md
        - Weapon images: development/game/assets/weapon-images.md
        - Weapon types and categories: development/game/assets/weapons-types-categories.md
    - Editor:
      - Build and run: development/editor/build-and-run.md
  - Imprint: /de/impressum/index.html
