site_name: Retro Carnage
site_url: http://www.retro-carnage.net/
site_dir: '../../generated/de'                      # Where to put the German HTML files
docs_dir: '../../docs/de'                           # Where to find the German markdown files

repo_url: https://github.com/Retro-Carnage-Team/retro-carnage-website
edit_uri: edit/master/docs/de/

theme:
  custom_dir: '../../overrides/'                    # This is where the customization of the theme lives
  favicon: assets/images/favicon.ico                # The favicon is shared by all languages
  features:
    - content.action.edit
    - content.action.view
  highlightjs: true
  language: de
  name: material  
  prev_next_buttons_location: none

extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en    
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:                                         
      lang: de                                      # Set language for search

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Download: download.md
  - Screenshots: screenshots.md
  - Development (🇬🇧):
    - Overview: /en/development/index.html
    - Game:
      - Build and run: /en/development/game/build-and-run/index.html
      - Assets:
        - Weapon images: /en/development/game/assets/weapon-images/index.html
        - Weapons: /en/development/game/assets/weapons/index.html
    - Editor:
      - Build and run: /en/development/editor/build-and-run/index.html
  - Impressum: impressum.md
