site_name: Retro Carnage
site_url: https://www.retro-carnage.net/de/
site_dir: '../../generated/de'
docs_dir: '../../docs/de'

theme:
  custom_dir: '../../overrides/'
  favicon: assets/images/favicon.ico
  highlightjs: true
  language: de
  name: material  
  prev_next_buttons_location: none

extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en    
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:                                         
      lang: de

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Download: download.md
  - Screenshots: screenshots.md
  - Development (🇬🇧):
    - Overview: /en/development/index.html
    - Game:
      - Assets:
        - Music and sound effects: /en/development/game/assets/sound-effects/index.html
        - Weapon configurations: /en/development/game/assets/weapon-configurations/index.html
        - Weapon images: /en/development/game/assets/weapon-images/index.html
        - Weapon types and categories: /en/development/game/assets/weapon-types-categories/index.html
        - Weapons compared: /en/development/game/assets/weapons-compared/index.html
      - User interface:
        - Screen flow: /en/development/game/ui/screen-flow/index.html
      - Build and run: /en/development/game/build-and-run/index.html
    - Editor:
      - Build and run: /en/development/editor/build-and-run/index.html
  - Impressum: impressum.md
