site_name: Retro Carnage
site_url: http://www.retro-carnage.net/
site_dir: '../../generated/de'                      # Where to put the German HTML files
docs_dir: '../../docs/de'                           # Where to find the German markdown files

repo_url: https://github.com/Retro-Carnage-Team/retro-carnage-website
edit_uri: edit/master/docs/de/

theme:
  custom_dir: '../../overrides/'                    # This is where the customization of the theme lives
  favicon: assets/images/favicon.ico                # The favicon is shared by all languages
  features:
    - content.action.edit
    - content.action.view
  highlightjs: true
  language: de
  name: material  
  prev_next_buttons_location: none

extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en    
  generator: false

plugins:
  - search:                                         
      lang: de                                      # Set language for search

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Download: downloads/index.md
  - Screenshots: screenshots.md
  - Entwicklung:
    - Overview: /../en/development/index.md
    - Game:
      - Build and run: /../en/development/game/build-and-run.md
    - Editor:
      - Build and run: /../en/development/editor/build-and-run.md
  - Impressum: impressum.md
