name: CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get -y install mkdocs git lftp
      - name: Install theme
        run: pip install mkdocs-material
      - name: Make the script files executable
        run: chmod +x ./build.sh ./buildBlog.sh ./buildFeed.sh ./upload.sh
      - name: Build website
        run: ./build.sh
      - name: Upload website
        run: ./upload.sh ${{vars.FTP_HOST}} ${{secrets.FTP_USER}} ${{secrets.FTP_PASS}}
