name: CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: sudo apt-get -y install pip mkdocs git lftp

      - name: Install theme
        run: pip install mkdocs-material

      - name: Build website
        run: mkdocs build -v -s

      - name: Make the script files executable
        run: chmod +x ./upload.sh

      - name: Upload website
        run: ./upload.sh ${{env.FTP_HOST}} ${{secrets.FTP_USER}} ${{secrets.FTP_PASS}}

