name: CI

on:
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get -y install pip mkdocs mkdocs-material mkdocs-material-extensions git
      - name: Build website
        run: mkdocs build -v -s
