name: CI

on:
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get -y install pip mkdocs git
      - name: Install theme
        run: pip install mkdocs-material
      - name: Make the script files executable
        run: chmod +x ./build.sh ./buildBlog.sh
      - name: Build website
        run: ./build.sh