name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: apt-get -y install pip mkdocs git

      - name: Build website
        run: mkdocs build -v -s
